name: "Backend - Dockerhub"
# triggers for action to run
on:
  push:
    branches: [ master ]

# workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:Project_Starter_Files-Building_a_Metrics_Dashboard/reference-app/backend"
        file: "./Dockerfile"
        #platforms: linux/amd64, linux/arm64
        push: true
        tags: rednotion/udacity_nd064_obs_backend:latest